import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import Link from 'next/link';
import { ReactNode } from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: '10px', maxHeight: '10vh', display: 'flex', justifyContent: 'space-between', background: '#eee', position: 'sticky', top: 0, zIndex: 1000 }}>
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            <h1>Enlisted Vehicle Guide</h1>
            <nav style={{ marginTop: '1.5rem' }}>
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/vehicles" id="vehicles">All vehicles</Link>
            </nav>
          </div>
          <img style={{ maxHeight: 'inherit', }} src="logo.jpg" alt="tank logo" />
        </header>

        <main style={{ padding: '1rem' }}>
          {children}
        </main>
        <footer style={{ paddingTop: '1rem', background: '#eee', position: 'absolute', zIndex: 1000, width: '100vw' }}>
          <div style={{ display: 'flex', alignItems: 'center', flexDirection: 'column', paddingTop: '2rem' }}>
            <p>This website is not affiliated with or endorsed by the game Enlisted.</p>
            <p>All trademarks and copyrights are the property of their respective owners.</p>
            <p>This website is for educational purposes only.</p>
            <p>The information provided on this website is for general informational purposes only.</p>
            <p>The author of this website is not responsible for any damage or loss of your vehicles whilst playing the game.</p>
            <p>The author if this website is not responsible for any lobbies you may annihilate with the knowledge found on this website</p>
            <p>© 2023 Vincent</p>
          </div>
        </footer>
      </body>
    </html>
  );
}